# Schema for the configuration files of the Formularios pruebas module.
formularios_pruebas.settings:
  type: config_object
  label: 'Formularios pruebas settings'
  mapping:
    example:
      type: string
      label: 'Example'
