<?php

/**
 * @file
 * Primary module hooks for Encuesta cgt module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function encuesta_cgt_theme() {
  return [
    'encuesta_cgt' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for encuesta cgt templates.
 *
 * Default template: encuesta-cgt.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the encuesta cgt information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_encuesta_cgt(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

