# Schema for the configuration files of the api_rest_block_bdns_filter module.
api_rest_block_bdns_filter.settings:
  type: config_object
  label: 'api_rest_block_bdns_filter settings'
  mapping:
    example:
      type: string
      label: 'Example Filter'